version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: estetica_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tualvidadasupersenha
      POSTGRES_DB: estetica_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: estetica_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:tualvidadasupersenha@db:5432/estetica_database?schema=public
      - JWT_SECRET=chave_secreta_ultra_segura_2026
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: estetica_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data: